#!/bin/sh

# Copyright (c) 2011 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

RESULT=0
chromeos-firmwareupdate --force --mode=factory_final || RESULT=$?
if [ "$RESULT" != "0" ]; then
  echo "Warning: firmware wiping failed with error code $RESULT."
fi
exit "$RESULT"
