#!/bin/sh
# Copyright 2017 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This is a template file which provides settings for firmware update of a
# particular model. The pack_firmware.py script uses this to create a working
# setvars-model.sh script.

# Version information for model REPLACE_MODEL
TARGET_RO_FWID="REPLACE_RO_FWID"
TARGET_FWID="REPLACE_FWID"
TARGET_ECID="REPLACE_ECID"
TARGET_PDID="REPLACE_PDID"
TARGET_PLATFORM="REPLACE_PLATFORM"
STABLE_FWID="REPLACE_STABLE_FWID"
STABLE_ECID="REPLACE_STABLE_ECID"
STABLE_PDID="REPLACE_STABLE_PDID"
