#!/bin/sh
# Copyright 2017 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# Purpose: Fake implementation of 'crossystem' tool

case "$1" in
  fwid)
    echo ${FAKE_FWID};;
  fw_vboot2\?1)
    [ "${FAKE_FW_VBOOT2}" = "1" ] || exit 1
    ;;
  hwid)
    echo ${FAKE_HWID};;
  mainfw_act)
    echo ${FAKE_MAINFW_ACT};;
  ro_fwid)
    echo ${FAKE_RO_FWID};;
  tpm_fwver)
    echo ${FAKE_TPM_FWVER};;
  vdat_flags)
    echo ${FAKE_VDAT_FLAGS};;
  wpsw_cur)
    echo ${FAKE_WPSW_CUR};;
  *)
    echo "Cannot handle command $1"
esac
