#!/bin/sh
# Copyright 2017 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# Purpose: Fake implementation of 'mosys' tool

case "$1" in
  platform)
    case "$2" in
      model)
        echo ${FAKE_MODEL};;
      *)
      echo "Cannot handle command $1 $2" >&2;;
    esac
    ;;
  *)
  echo "Cannot handle command $1" >&2;;
esac
